language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: kXCbwRflCv0BbClLy9l3siUgVaaoUTX0W7TJPnrij8Ndxw1uFh3JdjQb1D6yym99ZprV3BtSH+KVTOuA5XdSmQp+jQX2oO2BybQtRd/1MBYowmjLahFoYpKwO9xS4F7rRrHFmLOqNXY0d+xhZtTxtnZHmYDTK1rjNyh4COl2UzYQtWolPoTEno9WTJM8PR5yQohSUWUgxaVB2Yr36dTBfTQSXxihSRy0URC2gEwtj7P7DuBEQh4jukZLc5KT0TkHgTDv/qY+RZnKyTwE3/3wlEF3eLSiLCtCaV01lBcIjkKH/tnkaNO2yvPsQoyHm+MGpSwOH+dxPeqMvrZ50f/uT0u8TXaCXuFmsRStvsW059nx9BzBcGfXs2as9wvLL831z+cxoh+/dHqLZBXVR1zKs+cisNsqjTgRPCbUUrCGm2AhZqyloVPWO82THP5stqeW3bVu4K5dhn3wTtGnBRmpwpP6WEIKBYyxjyLzSidFS9QRSnyoW/U3hLfHJz29oBlwFznq0UOSocJJaM1PD6aRj2PBchrmq4OeKYytQI5fxs0nFEfg+KnyiE05HBMO61UbxyJV6IHDSCq7XtFieIQsktBwXjKPh3Rg/Jt3o7t6tHrsGCkSyaBEgXk7+bhQbVYW9kcq5DCsfaawPzUmwaqRkD3WDgRtLpXpfAXrshJz2w8=
  app: shoppingRecipeTest
  on:
    repo: LazyPupp/shoppingRecipeTest
